### ISSUE TITLE
OBC LoRa operation

### ISSUE THREAD

**Issue by emcauliffe** [MacRover/maxwell#15]
Confirm that teensy can communicate with LoRa chip (spi)

**Comment by chosterto** [comment]
2 of the LoRa Breakout Boards are confirmed to be working. The main issue was no connection between teensy and DIO1 which is necessary for interrupts when receiving packets. 

DIO connections of LoRa onboard the OBC are left floating. Might investigate with configuring Rx to bypass this issue.

**Comment by chosterto** [comment]
UPDATE: Can successfully communicate between OBC LoRa and LoRa board after connecting DIO1 to pin 3 of Teensy.
