### ISSUE TITLE
Setup Web Server

### ISSUE THREAD

**Issue by chosterto** [MacRover/maxwell#29]
Verify we can host a web server from the Teensy via Ethernet.

Use this example sketch from the NativeEthernet library for testing/reference:
https://github.com/vjmuzik/NativeEthernet/blob/master/examples/WebServer/WebServer.ino

Make sure you have this library added to your Arduino IDE (see https://github.com/MacRover/maxwell/wiki/Teensy-Setup#setting-up-micro-ros--libraries for details). On Arduino IDE, go to File > Examples > NativeEthernet > WebServer. Compile and upload this code to the teensy.

The website should be accessible from http://192.168.1.177:80

**Comment by chosterto** [comment]
Teensy successfully hosted a basic web server with @shadielfares help.

**Comment by shadielfares** [comment]
Teensy board with LoRa chip can successfully Transmit and Receive respectively, and asynchronously with @vaibhav-gopal help.

Works with Blocking and Transmit modes and can also do Ping-Pong example.
